package main

const (
	Msg_Error = iota

	Msg_Connecting
	Msg_ConnectSuccess
	Msg_ConnectFailed
	Msg_KickedOffline
	Msg_UserTokenExpired
	Msg_UserTokenInvalid

	Msg_SyncServerStart
	Msg_SyncServerFinish
	Msg_SyncServerProgress
	Msg_SyncServerFailed
	Msg_NewConversation
	Msg_ConversationChanged
	Msg_TotalUnreadMessageCountChanged
	Msg_ConversationUserInputStatusChanged

	Msg_Advanced_RecvNewMessage
	Msg_Advanced_RecvC2CReadReceipt
	Msg_Advanced_RecvGroupReadReceipt
	Msg_Advanced_NewRecvMessageRevoked
	Msg_Advanced_RecvMessageExtensionsChanged
	Msg_Advanced_RecvMessageExtensionsDeleted
	Msg_Advanced_RecvMessageExtensionsAdded
	Msg_Advanced_RecvOfflineNewMessage
	Msg_Advanced_MsgDeleted
	Msg_Advanced_RecvOnlineOnlyMessage

	Msg_Batch_RecvNewMessages
	Msg_Batch_RecvOfflineNewMessages

	Msg_FriendApplicationAdded
	Msg_FriendApplicationDeleted
	Msg_FriendApplicationAccepted
	Msg_FriendApplicationRejected
	Msg_FriendAdded
	Msg_FriendDeleted
	Msg_FriendInfoChanged
	Msg_BlackAdded
	Msg_BlackDeleted

	Msg_JoinedGroupAdded
	Msg_JoinedGroupDeleted
	Msg_GroupMemberAdded
	Msg_GroupMemberDeleted
	Msg_GroupApplicationAdded
	Msg_GroupApplicationDeleted
	Msg_GroupInfoChanged
	Msg_GroupDismissed
	Msg_GroupMemberInfoChanged
	Msg_GroupApplicationAccepted
	Msg_GroupApplicationRejected

	Msg_RecvCustomBusinessMessage

	Msg_SelfInfoUpdated
	Msg_UserStatusChanged
	Msg_UserCommandAdd
	Msg_UserCommandDelete
	Msg_UserCommandUpdate

	Msg_SendMessage_Error
	Msg_SendMessage_Success
	Msg_SendMessage_Progress

	Msg_ActiveCall
)

const (
	DataType_Empty = iota
	DataType_Int
	DataType_Bool
	DataType_StringArray
	DataType_Conversation
	DataType_Conversation_List
	DataType_FindMessageResult
	DataType_AdvancedHistoryMessageResult
	DataType_Message
	DataType_SearchMessagesResult
	DataType_UserInfo
	DataType_UserInfo_List
	DataType_PublicUserInfo
	DataType_PublicUserInfo_List
	DataType_OnlineStatus
	DataType_OnlineStatus_List
	DataType_SearchFriendItem
	DataType_SearchFriendItem_List
	DataType_UserIDResult
	DataType_UserIDResult_List
	DataType_FriendInfo
	DataType_FriendInfo_List
	DataType_FriendApplicationInfo
	DataType_FriendApplicationInfo_List
	DataType_BlackInfo
	DataType_BlackInfo_List
	DataType_GroupInfo
	DataType_GroupInfo_List
	DataType_GroupMember
	DataType_GroupMember_List
	DataType_GroupApplicationInfo
	DataType_GroupApplicationInfo_List
)
